services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'mb_dev'
      POSTGRES_USER: 'mbapp'
      POSTGRES_PASSWORD: 'mbapp_password'
      ADDITIONAL_POSTGRES_DBS: 'mb_test'
    volumes:
      - ./databases/init-scripts:/docker-entrypoint-initdb.d
      - ./.docker-data/.pg-data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: mbapp-rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.docker-data/.rabbit-data:/var/lib/rabbitmq/
      - ./.docker-data/.rabbit-log:/var/log/rabbitmq
      - ./.rabbit-plugins:/etc/rabbitmq/enabled_plugins
