services:
  basic-server:
    image: mbapp
    container_name: mbapp-web
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      APP: /opt/applications/basic-server.jar
  data-analyzer:
    image: mbapp
    container_name: mbapp-analyzer
    ports:
      - "8887:8887"
    environment:
      PORT: 8887
      APP: /opt/applications/data-analyzer-server.jar
  data-collector:
    image: mbapp
    container_name: mbapp-collector
    ports:
      - "8886:8886"
    environment:
      PORT: 8886
      APP: /opt/applications/data-collector-server.jar
