name: build-test
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - uses: hoverkraft-tech/compose-action@v2.0.1
      - name: "run migrations"
        run: ./gradlew testMigrate
      - name: "build"
        run: ./gradlew build
      - name: Archive test results basic-server
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: basic-server-test-report
          path: applications/basic-server/build/reports/tests/test/
      - name: Archive test results data-analyzer
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-analyzer-server-test-report
          path: applications/data-analyzer-server/build/reports/tests/test/

