name: build-test
on:
  push:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.8
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: './docker-compose-ci.yml'

      - name: "run migrations"
        run: ./gradlew testMigrate

      - name: "build"
        run: ./gradlew build
        env:
          RABBITMQ_HOST: 127.0.0.1
          RABBITMQ_PORT: ${{ job.services.rabbitmq.ports['5672'] }}

      - name: Archive test results basic-server
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: basic-server-test-report
          path: applications/basic-server/build/reports/tests/test/
      - name: Archive test results data-analyzer
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: data-analyzer-server-test-report
          path: applications/data-analyzer-server/build/reports/tests/test/

