name: deploy-review
on:
  push:
    branches:
      - main
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'
      - name: "build"
        run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: basic-server.jar
          path: applications/basic-server/build/libs/basic-server.jar
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: data-analyzer-server.jar
          path: applications/data-analyzer-server/build/libs/data-analyzer-server.jar
          retention-days: 1
      - uses: actions/upload-artifact@v4
        with:
          name: data-collector-server.jar
          path: applications/data-collector-server/build/libs/data-collector-server.jar
          retention-days: 1
  artifact-registry:
    runs-on: ubuntu-latest
    needs: [run-tests]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - uses: actions/download-artifact@v4
        with:
          name: basic-server.jar
          path: applications/basic-server/build/libs
      - uses: actions/download-artifact@v4
        with:
          name: data-analyzer-server.jar
          path: applications/data-analyzer-server/build/libs
      - uses: actions/download-artifact@v4
        with:
          name: data-collector-server.jar
          path: applications/data-collector-server/build/libs
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud"
  basic-server-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud"
  deploy-data-analyzer-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud"
  data-collector-review:
    runs-on: ubuntu-latest
    needs: [artifact-registry]
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/setup-gcloud@v2
      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          echo "gcloud"
